#!/bin/bash
# INSTRUCCIONES RÁPIDAS DE DEPLOY
# Estrategia: "Servidor como Fuente de Verdad" para SOS

echo "╔════════════════════════════════════════════════════════╗"
echo "║  DEPLOY: Flujo SOS \"Servidor como Fuente de Verdad\"   ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Paso 1: Deploy Backend (PRIMERO)
echo "┌─ PASO 1: Deploy Cloud Functions"
echo "│"
echo "│  cd functions"
echo "│  firebase deploy --only functions"
echo "│"
echo "│  ✓ Verifica logs en Firebase Console"
echo "│    → https://console.firebase.google.com/project/wilobu-d21b2/functions"
echo "│"
echo "│  ✓ Espera a que las funciones estén online"
echo "└─"
echo ""

# Paso 2: Flasheo Firmware (SEGUNDO)
echo "┌─ PASO 2: Flashear Firmware"
echo "│"
echo "│  cd wilobu_firmware"
echo "│  python -m platformio run --target upload"
echo "│"
echo "│  ✓ ESP32 recibirá nuevo firmware"
echo "│  ✓ Esperará vinculación o entrará en Idle"
echo "└─"
echo ""

# Paso 3: Testing (TERCERO)
echo "┌─ PASO 3: Validación Manual"
echo "│"
echo "│  1. Abrir Monitor Serial:"
echo "│     python -m platformio device monitor --baud 115200"
echo "│"
echo "│  2. Presionar botón SOS (hold 3 segundos)"
echo "│"
echo "│  3. Verificar en logs:"
echo "│     ✓ [SOS] DISPARO 1: Enviando alerta vacía..."
echo "│     ✓ [SOS] DISPARO 1 exitoso"
echo "│     ✓ [SOS] Iniciando búsqueda GPS..."
echo "│"
echo "│  4. En Firebase Console:"
echo "│     ✓ Ver documento actualizado con status='sos_general'"
echo "│     ✓ Ver lastLocation histórica preservada"
echo "│"
echo "│  5. En App Flutter:"
echo "│     ✓ Notificación debe llegar en < 5 segundos"
echo "│     ✓ Ubicación visible en mapa"
echo "│"
echo "│  6. Si hay GPS (Disparo 2):"
echo "│     ✓ Logs muestran: [SOS] GPS válido: ..."
echo "│     ✓ [SOS] DISPARO 2: Enviando ubicación precisa..."
echo "│     ✓ 2ª notificación con coordenadas nuevas"
echo "└─"
echo ""

# Paso 4: Monitoreo
echo "┌─ PASO 4: Monitoreo Continuo"
echo "│"
echo "│  1. Firestore Rules:"
echo "│     ✓ Permitir lectura de users/{uid}/devices"
echo "│     ✓ Permitir update de status y lastLocation"
echo "│"
echo "│  2. Cloud Functions:"
echo "│     ✓ Ver logs: firebase functions:log"
echo "│     ✓ Latencia debe ser < 500ms"
echo "│"
echo "│  3. Cloudflare Worker:"
echo "│     ✓ Ver tráfico: wrangler tail wilobu-proxy"
echo "│"
echo "│  4. App (Flutter):"
echo "│     ✓ Verificar FCM delivery"
echo "│     ✓ Revisar lastLocation update en tiempo real"
echo "└─"
echo ""

# Rollback
echo "╔════════════════════════════════════════════════════════╗"
echo "║  ROLLBACK (si es necesario)                            ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "1. Revertir Cloud Functions:"
echo "   cd functions"
echo "   git checkout HEAD^ index.js"
echo "   firebase deploy --only functions"
echo ""
echo "2. Reflashear firmware anterior:"
echo "   cd wilobu_firmware"
echo "   git checkout HEAD^ src/main.cpp"
echo "   python -m platformio run --target upload"
echo ""

echo "✅ DEPLOY COMPLETADO"
